### ISSUE TITLE
Problem with rs_set_key()

### ISSUE THREAD

**Issue by arildodias** [bluegreen-labs/appeears#16]
Hi, I tried to use the package but I think I made a mistake with the rs_set_key() just at the beginning of the tutorial. 

I used the rs_set_key() but then I got this error:

_Error in b_macos_set_with_value(self, private, service, username, password,  : 
  keyring error (macOS Keychain), cannot open keychain: The specified keychain could not be found._
  
Then I could not make the query. Any help is appreciated.

Thanks

**Comment by khufkens** [comment]
This seems like the {keychain} package, which does the heavy lifting for the key management, is confused (probably depends on how and if you have keychain configured).

Try the file based key management, as this if often a quick fix for these issues.
https://github.com/bluegreen-labs/appeears#file-based-keychains

**Comment by arildodias** [comment]
Thanks a lot. That fixing you suggested worked.

**Comment by khufkens** [comment]
Ok, closing this issue then.
