### ISSUE TITLE
ECOSTRESS products availability inconsistent 

### ISSUE THREAD

**Issue by monviso** [bluegreen-labs/appeears#20]
Hi,
This issue might not be related with the package, apologies in advance for this in case.

I am downloading ECOSTRESS data through R following roughly this procedure: https://cran.r-project.org/web/packages/appeears/vignettes/appeears_vignette.html .  
 
This is my reference data frame:
  task        subtask      start        end           product                  layer
1 polygon subtask 2024-08-01 2024-09-16 ECO2LSTE.001       SDS_LST
2 polygon subtask 2024-08-01 2024-09-16 ECO2LSTE.001   SDS_LST_err
3 polygon subtask 2024-08-01 2024-09-16 ECO2LSTE.001        SDS_QC
4 polygon subtask 2024-08-01 2024-09-16  ECO2CLD.001 SDS_CloudMask

 These layers are downloaded locally for specific AOI. Nonetheless, frequently (but not every time) I ended up with the following outputs (I report only .tif files):
.../ECO2CLD.001_SDS_CloudMask_doy2024224083616_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024231192938_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024232052159_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024243143940_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024247130507_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024251113240_aid0001.tif
.../ECO2CLD.001_SDS_CloudMask_doy2024255095959_aid0001.tif
.../ECO2LSTE.001_SDS_LST_doy2024243143940_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024224083616_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024231192938_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024232052159_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024243143940_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024247130507_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024251113240_aid0001.tif
.../ECO2LSTE.001_SDS_LST_err_doy2024255095959_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024224083616_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024231192938_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024232052159_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024243143940_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024247130507_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024251113240_aid0001.tif
.../ECO2LSTE.001_SDS_QC_doy2024255095959_aid0001.tif

As you can see, in the time range specified, there are 7 available observations for the cloudMask, error and quality layers, but only 1 is available for the LST product. Why is that? 
Thanks
Matteo

**Comment by khufkens** [comment]
Dear Matteo, I'm not familiar with the product in particular. But check if:

- multiple bands are included in the single LST product file (centered on the data requested)
- how the error and cloudmask and QC data is generated (and if this could be interpolated)
- does increasing time windows change the returned LST data

The package interacts with the API as is, no subsequent processing follows in R. So what you get is the output of Appeears - as is. So generally, issues with returned data are located upstream of the package.
